### ISSUE TITLE
Feature Request: Sending data with appID

### ISSUE THREAD

**Issue by robin-rrt** [availproject/avail-cli#1]
CLI currently does not support the option of submitting data for a particular appID. This leads to "Not Found" when trying to fetch data using cli LC configured to a particular appID.

**Comment by 0x0elliot** [comment]
how can i help here?

**Comment by cpp-phoenix** [comment]
@robin-rrt Please assign it to me

**Comment by QEDK** [comment]
AFAIK, this is already done
