### ISSUE TITLE
CLI: Update explorer link to current

### ISSUE THREAD

**Issue by vthunder** [availproject/avail-cli#10]
When submitting a tx, the cli posts an explorer link using an old domain:

```
$ avail data submit --network turing "testing"
✅ Blob included at block hash: 0x2699acd9f8cf3b46f0bfb114a8362f25c8dfa66ded3264231ba84e19854285ce
🧭 Link to explorer: https://turing.avail.tools/#/explorer/query/0x2699acd9f8cf3b46f0bfb114a8362f25c8dfa66ded3264231ba84e19854285ce
✅ Data blob sent to Avail
```

It should use `explorer.availproject.org` instead. I'm not sure if there's a way to hint to the explorer which network to use, if so it would be great to do that, otherwise it can be confusing.

**Comment by QEDK** [comment]
This has been resolved.
